name: Potential Duplicates
description: Search for potential issue duplicates.
author: bubkoo <bubkoo.wy@gmail.com> & happygirlzt
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  filter:
    description: Filter issues by title.
    required: false
  exclude:
    description: Exclude keywords in title before detecting.
    required: false
  label:
    description: Label to set, when potential duplicates are detected.
    default: potential-duplicate
    required: false
  state:
    description: "Get issues with state to compare. Supported state: 'all', 'closed', 'open'"
    default: all
    required: false
  threshold:
    description: Label color to set, when potential duplicates are detected.
    default: 0.6
    required: false
  comment:
    description: Comment to post when potential duplicates are detected.
    default: |
      Potential duplicates: {{#issues}}
        - [#{{ number }}] {{ title }} ({{ accuracy }}%)
      {{/issues}}
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: type
  color: yellow # gray-dark purple red orange green blue yellow black white
